# Task 1

In [1]:
#1.function to compute 5/0 and use try except to catch it
def fun():
    try:
        print(5/0)
    except ZeroDivisionError:
        print("exception catched")
fun()
        

In [2]:
#2.
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","cricket"]
print( *[i+' '+j+' '+k for i in subjects for j in verbs for k in objects],sep='\n')


Americans play Baseball
Americans play cricket
Americans watch Baseball
Americans watch cricket
Indians play Baseball
Indians play cricket
Indians watch Baseball
Indians watch cricket


# Task 2

In [3]:
#Alexandre Theophile Vandermode Matrix
#first column is x^(n-1) second is x^(n-2)... if increasing is false n viceversa
import numpy as np

def vandermonde_matrix(mtrx,n,b):
   if b=="false":
       mtrx=np.array(mtrx)
       for i in range(n):
           mtrx[:,i] **= n-i-1
   elif b=="true":
       print("Entered True")
       mtrx=np.array(mtrx)
       for i in range(n):
           mtrx[:,i] **= n-i-1
       mtrx[:,[0,n-1]] = mtrx[:,[n-1,0]]
   return mtrx.astype(int)

print("Enter array of elements")
arr=list(map(int,input().split()))
n=int(input("Enter n "))
b = input("Enter true/false ")
print(b)
np_arr = np.array(arr)
z = np.zeros((n,len(arr)))
arr = z+arr #broadcasting
mat = vandermonde_matrix(arr.T,n,b)
print("Vandermonde Matrix is : \n%s" %mat)

Enter array of elements
1 2 3 4 5 6
Enter n 4
Enter true/false false
false
Vandermonde Matrix is : 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
